allow negating FIRST(INTEGER) even though it overflows allows this test case to compile: C:\dev2\cm3.2\m3-sys\m3tests\src\p1\p137>cm3 --- building in NT386 ---
new source -> compiling Main.m3
"..\Main.m3", line 35: doneg: Negate overflowed
1 error encountered
compilation failed => not building program "pgm.exe"
Fatal Error: package build failed

tempting to make TInt.Add/Subtract return the value
even if overflow, but for now, no.
This fix assumes two's complement, that is,
it assumes FIRST(INTEGER) = -FIRST(INTEGER)