tests: Fix p211 to compile, warning/error unused value.
C.c:103:56: error: expression result unused [-Werror,-Wunused-value]
printf("string not found %s/n", (Type ? "double" : "float", String));