m3tohtml:   Main.m3: In function ‘Main__ReadFileList__AddFile__Add’:   Main.m3:151: error: ‘struct Main__ReadFileList__AddFile_Frame_t’ has no member named ‘_static_link’   Main.m3:155: error: ‘struct Main__ReadFileList__AddFile_Frame_t’ has no member named ‘_static_link’
mark static_link parameter as always used, so that
it always gets a place in the frame

(fallout from removing unused variables -- at which time,
I guess, I also optimized away other stuff..unused uplevel locals
spot in frame?)