add missing "end" statement at line 58 to correct compile-time syntax error.
Someone needs to check me on this one.  After this change, I don't get any packages built in cvsup on WindowsXP, I suppose due to some prerequiste not being met.  But at least I don't get the syntax error.

Not sure why the package m3makefile seems to be limited to POSIX platforms at line 31.  Everything was building on Windows before.--R.Coleburn

Here is the compiler output before my correction:

C:\cm3\Sandbox\cm3\m3-tools\cvsup\suplib>cm3 -verbose
EVAL ("C:\cm3\bin\cm3.cfg")
--- building in NT386 ---

cd NT386
LIB_INSTALL is C:\cm3\lib
ignoring ..\src\m3overrides

EVAL ("m3make.args")
rm .M3SHIP
rm .M3OVERRIDES
"C:\cm3\Sandbox\cm3\m3-tools\cvsup\suplib\NT386\m3make.args", line 5: quake runtime error: C:\cm3\Sandbox\cm3\m3-tools\cvsup\suplib\src\m3makefile, line 263: syntax error: "end" or "else" expected after "if"

--procedure--  -line-  -file---
include_dir        --  <builtin>
                    5  C:\cm3\Sandbox\cm3\m3-tools\cvsup\suplib\NT386\m3make.args

Fatal Error: package build failed

 seconds  #times  operation
    0.03       2  removing temporary files
    0.03          other
---------------------------------------------------
    0.06          TOTAL

rm m3make.args
cd ..

C:\cm3\Sandbox\cm3\m3-tools\cvsup\suplib>