Compatability with Unicode branch.
Recognize the magic string in m3linker files (*.mx, *.m3x) for Unicode-sized
WIDECHAR.  Without this change, the head compiler would already detect an
attempt to link in code compiled with Unicode-sized WIDECHAR, but with a highly
uninformative message, similar to:

Fatal Error: bad link info file: /usr/local/cm3/pkg/web/AMD64_LINUX/libweb.m3x

Similarly, when recompiling a package that was previously compiled with
Unicode-sized WIDECHAR, the head compiler would recompile the entire package,
but with no meaningful explanation.

With these changes, the head compiler gives comprehensible messages in these
situations.

Note: This mechanism only detects what compiler version (16-bit WIDECHAR or
Unicode-WIDECHAR) was used, without regard to whether there are actually
any WIDECHAR variables in the package(s) being linked/recompiled or whether
such values cross package boundaries.

The release compiler, with no modifications, should handle these cases too,
but without helpful messages.

This code is almost identical in the head and Unicode branches, except for
the value of CONST Mx.UnicodeWideChar, which needs to agree with settings
in m3front and m3cc.