m3core: Fix compiling Umman.c on most systems due to Solaris fix.
../src/unix/Common/Umman.c: In function cchar* Umman__mmap(caddr_t, WORD_T, int, int, int, m3_off_t):
../src/m3core.h:315:106: error: invalid conversion from void* to ADDRESS (char*)

Keep the parameters char*, which converts to void*.
But make the return void*, which converts from char*.