Change the magic string in m3lnker files (*.mx, *.m3x) for Unicode-sized WIDECHAR.  This means attempts to link together code compiled with different sizes of WIDECHAR will be detected at link time.
When compiling/linking using the unicode branch, the message will be
informative.  When compiling using the release or head compiler, it will
be uninformative, something like:

Fatal Error: bad link info file: /usr/local/cm3/pkg/web/AMD64_LINUX/libweb.m3x

With one change to CONST Mx.UnicodeWideChar, these files can work in older
compilers, leading to informative messages from them too.

Note: This will be treated as a link failure without regard to whether there
are actually any WIDECHAR variables in the package(s) being linked.  It only
matters what compiler version they were compiled with.